# Generated by Django 5.2.5 on 2025-08-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20250824_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='userid',
            new_name='user',
        ),
    ]
